// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: v1/reply.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Reply_AddReply_FullMethodName             = "/comment.sdk.v1.Reply/AddReply"
	Reply_DelReply_FullMethodName             = "/comment.sdk.v1.Reply/DelReply"
	Reply_LikeAction_FullMethodName           = "/comment.sdk.v1.Reply/LikeAction"
	Reply_DislikeAction_FullMethodName        = "/comment.sdk.v1.Reply/DislikeAction"
	Reply_ReportReply_FullMethodName          = "/comment.sdk.v1.Reply/ReportReply"
	Reply_PinReply_FullMethodName             = "/comment.sdk.v1.Reply/PinReply"
	Reply_PageGetReply_FullMethodName         = "/comment.sdk.v1.Reply/PageGetReply"
	Reply_PageGetSubReply_FullMethodName      = "/comment.sdk.v1.Reply/PageGetSubReply"
	Reply_PageGetDetailedReply_FullMethodName = "/comment.sdk.v1.Reply/PageGetDetailedReply"
	Reply_GetPinnedReply_FullMethodName       = "/comment.sdk.v1.Reply/GetPinnedReply"
	Reply_CountReply_FullMethodName           = "/comment.sdk.v1.Reply/CountReply"
)

// ReplyClient is the client API for Reply service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReplyClient interface {
	// 发表评论
	AddReply(ctx context.Context, in *AddReplyReq, opts ...grpc.CallOption) (*AddReplyRes, error)
	// 删除评论
	DelReply(ctx context.Context, in *DelReplyReq, opts ...grpc.CallOption) (*DelReplyRes, error)
	// 赞
	LikeAction(ctx context.Context, in *LikeActionReq, opts ...grpc.CallOption) (*LikeActionRes, error)
	// 踩
	DislikeAction(ctx context.Context, in *DislikeActionReq, opts ...grpc.CallOption) (*DislikeActionRes, error)
	// 举报
	ReportReply(ctx context.Context, in *ReportReplyReq, opts ...grpc.CallOption) (*ReportReplyRes, error)
	// 置顶评论
	PinReply(ctx context.Context, in *PinReplyReq, opts ...grpc.CallOption) (*PinReplyRes, error)
	// 获取主评论信息
	PageGetReply(ctx context.Context, in *PageGetReplyReq, opts ...grpc.CallOption) (*PageGetReplyRes, error)
	// 获取子评论信息
	PageGetSubReply(ctx context.Context, in *PageGetSubReplyReq, opts ...grpc.CallOption) (*PageGetSubReplyRes, error)
	// 获取主评论详细信息
	PageGetDetailedReply(ctx context.Context, in *PageGetReplyReq, opts ...grpc.CallOption) (*PageGetDetailedReplyRes, error)
	// 获取置顶评论
	GetPinnedReply(ctx context.Context, in *GetPinnedReplyReq, opts ...grpc.CallOption) (*GetPinnedReplyRes, error)
	// 获取某个被评对象的评论数
	CountReply(ctx context.Context, in *CountReplyReq, opts ...grpc.CallOption) (*CountReplyRes, error)
}

type replyClient struct {
	cc grpc.ClientConnInterface
}

func NewReplyClient(cc grpc.ClientConnInterface) ReplyClient {
	return &replyClient{cc}
}

func (c *replyClient) AddReply(ctx context.Context, in *AddReplyReq, opts ...grpc.CallOption) (*AddReplyRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddReplyRes)
	err := c.cc.Invoke(ctx, Reply_AddReply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replyClient) DelReply(ctx context.Context, in *DelReplyReq, opts ...grpc.CallOption) (*DelReplyRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelReplyRes)
	err := c.cc.Invoke(ctx, Reply_DelReply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replyClient) LikeAction(ctx context.Context, in *LikeActionReq, opts ...grpc.CallOption) (*LikeActionRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LikeActionRes)
	err := c.cc.Invoke(ctx, Reply_LikeAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replyClient) DislikeAction(ctx context.Context, in *DislikeActionReq, opts ...grpc.CallOption) (*DislikeActionRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DislikeActionRes)
	err := c.cc.Invoke(ctx, Reply_DislikeAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replyClient) ReportReply(ctx context.Context, in *ReportReplyReq, opts ...grpc.CallOption) (*ReportReplyRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportReplyRes)
	err := c.cc.Invoke(ctx, Reply_ReportReply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replyClient) PinReply(ctx context.Context, in *PinReplyReq, opts ...grpc.CallOption) (*PinReplyRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PinReplyRes)
	err := c.cc.Invoke(ctx, Reply_PinReply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replyClient) PageGetReply(ctx context.Context, in *PageGetReplyReq, opts ...grpc.CallOption) (*PageGetReplyRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PageGetReplyRes)
	err := c.cc.Invoke(ctx, Reply_PageGetReply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replyClient) PageGetSubReply(ctx context.Context, in *PageGetSubReplyReq, opts ...grpc.CallOption) (*PageGetSubReplyRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PageGetSubReplyRes)
	err := c.cc.Invoke(ctx, Reply_PageGetSubReply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replyClient) PageGetDetailedReply(ctx context.Context, in *PageGetReplyReq, opts ...grpc.CallOption) (*PageGetDetailedReplyRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PageGetDetailedReplyRes)
	err := c.cc.Invoke(ctx, Reply_PageGetDetailedReply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replyClient) GetPinnedReply(ctx context.Context, in *GetPinnedReplyReq, opts ...grpc.CallOption) (*GetPinnedReplyRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPinnedReplyRes)
	err := c.cc.Invoke(ctx, Reply_GetPinnedReply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replyClient) CountReply(ctx context.Context, in *CountReplyReq, opts ...grpc.CallOption) (*CountReplyRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountReplyRes)
	err := c.cc.Invoke(ctx, Reply_CountReply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReplyServer is the server API for Reply service.
// All implementations must embed UnimplementedReplyServer
// for forward compatibility.
type ReplyServer interface {
	// 发表评论
	AddReply(context.Context, *AddReplyReq) (*AddReplyRes, error)
	// 删除评论
	DelReply(context.Context, *DelReplyReq) (*DelReplyRes, error)
	// 赞
	LikeAction(context.Context, *LikeActionReq) (*LikeActionRes, error)
	// 踩
	DislikeAction(context.Context, *DislikeActionReq) (*DislikeActionRes, error)
	// 举报
	ReportReply(context.Context, *ReportReplyReq) (*ReportReplyRes, error)
	// 置顶评论
	PinReply(context.Context, *PinReplyReq) (*PinReplyRes, error)
	// 获取主评论信息
	PageGetReply(context.Context, *PageGetReplyReq) (*PageGetReplyRes, error)
	// 获取子评论信息
	PageGetSubReply(context.Context, *PageGetSubReplyReq) (*PageGetSubReplyRes, error)
	// 获取主评论详细信息
	PageGetDetailedReply(context.Context, *PageGetReplyReq) (*PageGetDetailedReplyRes, error)
	// 获取置顶评论
	GetPinnedReply(context.Context, *GetPinnedReplyReq) (*GetPinnedReplyRes, error)
	// 获取某个被评对象的评论数
	CountReply(context.Context, *CountReplyReq) (*CountReplyRes, error)
	mustEmbedUnimplementedReplyServer()
}

// UnimplementedReplyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReplyServer struct{}

func (UnimplementedReplyServer) AddReply(context.Context, *AddReplyReq) (*AddReplyRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddReply not implemented")
}
func (UnimplementedReplyServer) DelReply(context.Context, *DelReplyReq) (*DelReplyRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelReply not implemented")
}
func (UnimplementedReplyServer) LikeAction(context.Context, *LikeActionReq) (*LikeActionRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LikeAction not implemented")
}
func (UnimplementedReplyServer) DislikeAction(context.Context, *DislikeActionReq) (*DislikeActionRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DislikeAction not implemented")
}
func (UnimplementedReplyServer) ReportReply(context.Context, *ReportReplyReq) (*ReportReplyRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportReply not implemented")
}
func (UnimplementedReplyServer) PinReply(context.Context, *PinReplyReq) (*PinReplyRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PinReply not implemented")
}
func (UnimplementedReplyServer) PageGetReply(context.Context, *PageGetReplyReq) (*PageGetReplyRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PageGetReply not implemented")
}
func (UnimplementedReplyServer) PageGetSubReply(context.Context, *PageGetSubReplyReq) (*PageGetSubReplyRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PageGetSubReply not implemented")
}
func (UnimplementedReplyServer) PageGetDetailedReply(context.Context, *PageGetReplyReq) (*PageGetDetailedReplyRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PageGetDetailedReply not implemented")
}
func (UnimplementedReplyServer) GetPinnedReply(context.Context, *GetPinnedReplyReq) (*GetPinnedReplyRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPinnedReply not implemented")
}
func (UnimplementedReplyServer) CountReply(context.Context, *CountReplyReq) (*CountReplyRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CountReply not implemented")
}
func (UnimplementedReplyServer) mustEmbedUnimplementedReplyServer() {}
func (UnimplementedReplyServer) testEmbeddedByValue()               {}

// UnsafeReplyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReplyServer will
// result in compilation errors.
type UnsafeReplyServer interface {
	mustEmbedUnimplementedReplyServer()
}

func RegisterReplyServer(s grpc.ServiceRegistrar, srv ReplyServer) {
	// If the following call pancis, it indicates UnimplementedReplyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Reply_ServiceDesc, srv)
}

func _Reply_AddReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddReplyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplyServer).AddReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Reply_AddReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplyServer).AddReply(ctx, req.(*AddReplyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reply_DelReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelReplyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplyServer).DelReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Reply_DelReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplyServer).DelReply(ctx, req.(*DelReplyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reply_LikeAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeActionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplyServer).LikeAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Reply_LikeAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplyServer).LikeAction(ctx, req.(*LikeActionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reply_DislikeAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DislikeActionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplyServer).DislikeAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Reply_DislikeAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplyServer).DislikeAction(ctx, req.(*DislikeActionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reply_ReportReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportReplyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplyServer).ReportReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Reply_ReportReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplyServer).ReportReply(ctx, req.(*ReportReplyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reply_PinReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PinReplyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplyServer).PinReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Reply_PinReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplyServer).PinReply(ctx, req.(*PinReplyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reply_PageGetReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageGetReplyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplyServer).PageGetReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Reply_PageGetReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplyServer).PageGetReply(ctx, req.(*PageGetReplyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reply_PageGetSubReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageGetSubReplyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplyServer).PageGetSubReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Reply_PageGetSubReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplyServer).PageGetSubReply(ctx, req.(*PageGetSubReplyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reply_PageGetDetailedReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageGetReplyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplyServer).PageGetDetailedReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Reply_PageGetDetailedReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplyServer).PageGetDetailedReply(ctx, req.(*PageGetReplyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reply_GetPinnedReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPinnedReplyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplyServer).GetPinnedReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Reply_GetPinnedReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplyServer).GetPinnedReply(ctx, req.(*GetPinnedReplyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reply_CountReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountReplyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplyServer).CountReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Reply_CountReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplyServer).CountReply(ctx, req.(*CountReplyReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Reply_ServiceDesc is the grpc.ServiceDesc for Reply service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Reply_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "comment.sdk.v1.Reply",
	HandlerType: (*ReplyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddReply",
			Handler:    _Reply_AddReply_Handler,
		},
		{
			MethodName: "DelReply",
			Handler:    _Reply_DelReply_Handler,
		},
		{
			MethodName: "LikeAction",
			Handler:    _Reply_LikeAction_Handler,
		},
		{
			MethodName: "DislikeAction",
			Handler:    _Reply_DislikeAction_Handler,
		},
		{
			MethodName: "ReportReply",
			Handler:    _Reply_ReportReply_Handler,
		},
		{
			MethodName: "PinReply",
			Handler:    _Reply_PinReply_Handler,
		},
		{
			MethodName: "PageGetReply",
			Handler:    _Reply_PageGetReply_Handler,
		},
		{
			MethodName: "PageGetSubReply",
			Handler:    _Reply_PageGetSubReply_Handler,
		},
		{
			MethodName: "PageGetDetailedReply",
			Handler:    _Reply_PageGetDetailedReply_Handler,
		},
		{
			MethodName: "GetPinnedReply",
			Handler:    _Reply_GetPinnedReply_Handler,
		},
		{
			MethodName: "CountReply",
			Handler:    _Reply_CountReply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/reply.proto",
}
