// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: forward/v1/forward.proto

package v1

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

// ForwardServiceClient is the client API for ForwardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ForwardServiceClient interface {
}

type forwardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewForwardServiceClient(cc grpc.ClientConnInterface) ForwardServiceClient {
	return &forwardServiceClient{cc}
}

// ForwardServiceServer is the server API for ForwardService service.
// All implementations must embed UnimplementedForwardServiceServer
// for forward compatibility.
type ForwardServiceServer interface {
	mustEmbedUnimplementedForwardServiceServer()
}

// UnimplementedForwardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedForwardServiceServer struct{}

func (UnimplementedForwardServiceServer) mustEmbedUnimplementedForwardServiceServer() {}
func (UnimplementedForwardServiceServer) testEmbeddedByValue()                        {}

// UnsafeForwardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ForwardServiceServer will
// result in compilation errors.
type UnsafeForwardServiceServer interface {
	mustEmbedUnimplementedForwardServiceServer()
}

func RegisterForwardServiceServer(s grpc.ServiceRegistrar, srv ForwardServiceServer) {
	// If the following call pancis, it indicates UnimplementedForwardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ForwardService_ServiceDesc, srv)
}

// ForwardService_ServiceDesc is the grpc.ServiceDesc for ForwardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ForwardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wslink.api.forward.v1.ForwardService",
	HandlerType: (*ForwardServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "forward/v1/forward.proto",
}
