package grpc

import commentv1 "github.com/ryanreadbooks/whimer/comment/api/v1"

// 定义不需要检查uid的方法
var uidCheckIgnoredMethods = []string{
	commentv1.CommentService_PageGetComment_FullMethodName,
	commentv1.CommentService_PageGetSubComment_FullMethodName,
	commentv1.CommentService_PageGetDetailedComment_FullMethodName,
	commentv1.CommentService_GetPinnedComment_FullMethodName,
	commentv1.CommentService_CountComment_FullMethodName,
	commentv1.CommentService_BatchCountComment_FullMethodName,
	commentv1.CommentService_GetCommentLikeCount_FullMethodName,
	commentv1.CommentService_GetCommentDislikeCount_FullMethodName,
	commentv1.CommentService_CheckUserOnObject_FullMethodName,
	commentv1.CommentService_BatchCheckUserOnObject_FullMethodName,
}
