CREATE TABLE IF NOT EXISTS note (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`title` VARCHAR(48) NOT NULL DEFAULT '' COMMENT '标题',
	`desc` VARCHAR(2048) NOT NULL DEFAULT '' COMMENT '描述',
	`privacy` TINYINT NOT NULL DEFAULT 0 COMMENT '公开类型',
	`owner` BIGINT NOT NULL DEFAULT 0 COMMENT '笔记作者',
	`create_at` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间',
	`update_at` BIGINT NOT NULL DEFAULT 0 COMMENT '更新时间',
	PRIMARY KEY (`id`),
	KEY idx_owner(`owner`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='笔记表';
