CREATE TABLE IF NOT EXISTS note (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`title` VARCHAR(48) NOT NULL DEFAULT '' COMMENT '标题',
	`desc` VARCHAR(2048) NOT NULL DEFAULT '' COMMENT '描述',
	`privacy` TINYINT NOT NULL DEFAULT 0 COMMENT '公开类型',
	`create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='笔记表';