grpc:
  mode: dev
  name: search-rpc
  listenon: 0.0.0.0:10009
  log:
    level: debug
  etcd:
    hosts: ${ENV_ETCD_HOSTS}
    key: whimer.search.rpc
  telemetry:
    Name: search
    Endpoint: ${ENV_JAEGER_ENDPOINT}
    Sampler: 1.0
    Batcher: jaeger

elasticsearch:
  addr: ${ENV_ES_ADDR}
  user: ${ENV_ES_USER}
  password: ${ENV_ES_PASSWORD}

kafka:
  brokers: ${ENV_KFK_BROKERS}
  username: ${ENV_KFK_USERNAME}
  password: ${ENV_KFK_PASSWORD}

consumer_topic_config:
  es_note_event:
    batch_size: 50
    batch_timeout: 2s
