// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: v1/note.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IsUserOwnNoteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid    uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`                     // 用户id
	NoteId uint64 `protobuf:"varint,2,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"` // 笔记id
}

func (x *IsUserOwnNoteReq) Reset() {
	*x = IsUserOwnNoteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_note_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsUserOwnNoteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsUserOwnNoteReq) ProtoMessage() {}

func (x *IsUserOwnNoteReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_note_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsUserOwnNoteReq.ProtoReflect.Descriptor instead.
func (*IsUserOwnNoteReq) Descriptor() ([]byte, []int) {
	return file_v1_note_proto_rawDescGZIP(), []int{0}
}

func (x *IsUserOwnNoteReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *IsUserOwnNoteReq) GetNoteId() uint64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

type IsUserOwnNoteRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid    uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Result bool   `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"` // 结果
}

func (x *IsUserOwnNoteRes) Reset() {
	*x = IsUserOwnNoteRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_note_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsUserOwnNoteRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsUserOwnNoteRes) ProtoMessage() {}

func (x *IsUserOwnNoteRes) ProtoReflect() protoreflect.Message {
	mi := &file_v1_note_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsUserOwnNoteRes.ProtoReflect.Descriptor instead.
func (*IsUserOwnNoteRes) Descriptor() ([]byte, []int) {
	return file_v1_note_proto_rawDescGZIP(), []int{1}
}

func (x *IsUserOwnNoteRes) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *IsUserOwnNoteRes) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type IsNoteExistReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NoteId uint64 `protobuf:"varint,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
}

func (x *IsNoteExistReq) Reset() {
	*x = IsNoteExistReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_note_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsNoteExistReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsNoteExistReq) ProtoMessage() {}

func (x *IsNoteExistReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_note_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsNoteExistReq.ProtoReflect.Descriptor instead.
func (*IsNoteExistReq) Descriptor() ([]byte, []int) {
	return file_v1_note_proto_rawDescGZIP(), []int{2}
}

func (x *IsNoteExistReq) GetNoteId() uint64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

type IsNoteExistRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exist bool `protobuf:"varint,1,opt,name=exist,proto3" json:"exist,omitempty"`
}

func (x *IsNoteExistRes) Reset() {
	*x = IsNoteExistRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_note_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsNoteExistRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsNoteExistRes) ProtoMessage() {}

func (x *IsNoteExistRes) ProtoReflect() protoreflect.Message {
	mi := &file_v1_note_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsNoteExistRes.ProtoReflect.Descriptor instead.
func (*IsNoteExistRes) Descriptor() ([]byte, []int) {
	return file_v1_note_proto_rawDescGZIP(), []int{3}
}

func (x *IsNoteExistRes) GetExist() bool {
	if x != nil {
		return x.Exist
	}
	return false
}

type CreateReqBasic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title   string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Desc    string `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	Privacy int32  `protobuf:"varint,3,opt,name=privacy,proto3" json:"privacy,omitempty"`
}

func (x *CreateReqBasic) Reset() {
	*x = CreateReqBasic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_note_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateReqBasic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReqBasic) ProtoMessage() {}

func (x *CreateReqBasic) ProtoReflect() protoreflect.Message {
	mi := &file_v1_note_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReqBasic.ProtoReflect.Descriptor instead.
func (*CreateReqBasic) Descriptor() ([]byte, []int) {
	return file_v1_note_proto_rawDescGZIP(), []int{4}
}

func (x *CreateReqBasic) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateReqBasic) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *CreateReqBasic) GetPrivacy() int32 {
	if x != nil {
		return x.Privacy
	}
	return 0
}

type CreateReqImage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileId string `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
}

func (x *CreateReqImage) Reset() {
	*x = CreateReqImage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_note_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateReqImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReqImage) ProtoMessage() {}

func (x *CreateReqImage) ProtoReflect() protoreflect.Message {
	mi := &file_v1_note_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReqImage.ProtoReflect.Descriptor instead.
func (*CreateReqImage) Descriptor() ([]byte, []int) {
	return file_v1_note_proto_rawDescGZIP(), []int{5}
}

func (x *CreateReqImage) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type CreateNoteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Basic  *CreateReqBasic   `protobuf:"bytes,1,opt,name=basic,proto3" json:"basic,omitempty"`
	Images []*CreateReqImage `protobuf:"bytes,2,rep,name=images,proto3" json:"images,omitempty"`
}

func (x *CreateNoteReq) Reset() {
	*x = CreateNoteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_note_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNoteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNoteReq) ProtoMessage() {}

func (x *CreateNoteReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_note_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNoteReq.ProtoReflect.Descriptor instead.
func (*CreateNoteReq) Descriptor() ([]byte, []int) {
	return file_v1_note_proto_rawDescGZIP(), []int{6}
}

func (x *CreateNoteReq) GetBasic() *CreateReqBasic {
	if x != nil {
		return x.Basic
	}
	return nil
}

func (x *CreateNoteReq) GetImages() []*CreateReqImage {
	if x != nil {
		return x.Images
	}
	return nil
}

type CreateNoteRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NoteId uint64 `protobuf:"varint,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
}

func (x *CreateNoteRes) Reset() {
	*x = CreateNoteRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_note_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNoteRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNoteRes) ProtoMessage() {}

func (x *CreateNoteRes) ProtoReflect() protoreflect.Message {
	mi := &file_v1_note_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNoteRes.ProtoReflect.Descriptor instead.
func (*CreateNoteRes) Descriptor() ([]byte, []int) {
	return file_v1_note_proto_rawDescGZIP(), []int{7}
}

func (x *CreateNoteRes) GetNoteId() uint64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

type DeleteNoteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NoteId uint64 `protobuf:"varint,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
}

func (x *DeleteNoteReq) Reset() {
	*x = DeleteNoteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_note_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteNoteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNoteReq) ProtoMessage() {}

func (x *DeleteNoteReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_note_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNoteReq.ProtoReflect.Descriptor instead.
func (*DeleteNoteReq) Descriptor() ([]byte, []int) {
	return file_v1_note_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteNoteReq) GetNoteId() uint64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

type DeleteNoteRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteNoteRes) Reset() {
	*x = DeleteNoteRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_note_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteNoteRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNoteRes) ProtoMessage() {}

func (x *DeleteNoteRes) ProtoReflect() protoreflect.Message {
	mi := &file_v1_note_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNoteRes.ProtoReflect.Descriptor instead.
func (*DeleteNoteRes) Descriptor() ([]byte, []int) {
	return file_v1_note_proto_rawDescGZIP(), []int{9}
}

type UpdateNoteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NoteId uint64         `protobuf:"varint,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	Note   *CreateNoteReq `protobuf:"bytes,2,opt,name=note,proto3" json:"note,omitempty"`
}

func (x *UpdateNoteReq) Reset() {
	*x = UpdateNoteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_note_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateNoteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNoteReq) ProtoMessage() {}

func (x *UpdateNoteReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_note_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNoteReq.ProtoReflect.Descriptor instead.
func (*UpdateNoteReq) Descriptor() ([]byte, []int) {
	return file_v1_note_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateNoteReq) GetNoteId() uint64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

func (x *UpdateNoteReq) GetNote() *CreateNoteReq {
	if x != nil {
		return x.Note
	}
	return nil
}

type UpdateNoteRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NoteId uint64 `protobuf:"varint,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
}

func (x *UpdateNoteRes) Reset() {
	*x = UpdateNoteRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_note_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateNoteRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNoteRes) ProtoMessage() {}

func (x *UpdateNoteRes) ProtoReflect() protoreflect.Message {
	mi := &file_v1_note_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNoteRes.ProtoReflect.Descriptor instead.
func (*UpdateNoteRes) Descriptor() ([]byte, []int) {
	return file_v1_note_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateNoteRes) GetNoteId() uint64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

type GetNoteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NoteId uint64 `protobuf:"varint,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
}

func (x *GetNoteReq) Reset() {
	*x = GetNoteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_note_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNoteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNoteReq) ProtoMessage() {}

func (x *GetNoteReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_note_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNoteReq.ProtoReflect.Descriptor instead.
func (*GetNoteReq) Descriptor() ([]byte, []int) {
	return file_v1_note_proto_rawDescGZIP(), []int{12}
}

func (x *GetNoteReq) GetNoteId() uint64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

type GetNoteResImage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url  string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Type int32  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *GetNoteResImage) Reset() {
	*x = GetNoteResImage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_note_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNoteResImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNoteResImage) ProtoMessage() {}

func (x *GetNoteResImage) ProtoReflect() protoreflect.Message {
	mi := &file_v1_note_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNoteResImage.ProtoReflect.Descriptor instead.
func (*GetNoteResImage) Descriptor() ([]byte, []int) {
	return file_v1_note_proto_rawDescGZIP(), []int{13}
}

func (x *GetNoteResImage) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetNoteResImage) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type NoteItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NoteId   uint64             `protobuf:"varint,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	Title    string             `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Desc     string             `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	Privacy  int32              `protobuf:"varint,4,opt,name=privacy,proto3" json:"privacy,omitempty"`
	CreateAt int64              `protobuf:"varint,5,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	UpdateAt int64              `protobuf:"varint,6,opt,name=update_at,json=updateAt,proto3" json:"update_at,omitempty"`
	Images   []*GetNoteResImage `protobuf:"bytes,7,rep,name=images,proto3" json:"images,omitempty"`
}

func (x *NoteItem) Reset() {
	*x = NoteItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_note_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoteItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteItem) ProtoMessage() {}

func (x *NoteItem) ProtoReflect() protoreflect.Message {
	mi := &file_v1_note_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteItem.ProtoReflect.Descriptor instead.
func (*NoteItem) Descriptor() ([]byte, []int) {
	return file_v1_note_proto_rawDescGZIP(), []int{14}
}

func (x *NoteItem) GetNoteId() uint64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

func (x *NoteItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NoteItem) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *NoteItem) GetPrivacy() int32 {
	if x != nil {
		return x.Privacy
	}
	return 0
}

func (x *NoteItem) GetCreateAt() int64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

func (x *NoteItem) GetUpdateAt() int64 {
	if x != nil {
		return x.UpdateAt
	}
	return 0
}

func (x *NoteItem) GetImages() []*GetNoteResImage {
	if x != nil {
		return x.Images
	}
	return nil
}

type ListNoteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListNoteReq) Reset() {
	*x = ListNoteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_note_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListNoteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNoteReq) ProtoMessage() {}

func (x *ListNoteReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_note_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNoteReq.ProtoReflect.Descriptor instead.
func (*ListNoteReq) Descriptor() ([]byte, []int) {
	return file_v1_note_proto_rawDescGZIP(), []int{15}
}

type ListNoteRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*NoteItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ListNoteRes) Reset() {
	*x = ListNoteRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_note_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListNoteRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNoteRes) ProtoMessage() {}

func (x *ListNoteRes) ProtoReflect() protoreflect.Message {
	mi := &file_v1_note_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNoteRes.ProtoReflect.Descriptor instead.
func (*ListNoteRes) Descriptor() ([]byte, []int) {
	return file_v1_note_proto_rawDescGZIP(), []int{16}
}

func (x *ListNoteRes) GetItems() []*NoteItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetUploadAuthReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resource string `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Source   string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	MimeType string `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
}

func (x *GetUploadAuthReq) Reset() {
	*x = GetUploadAuthReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_note_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUploadAuthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadAuthReq) ProtoMessage() {}

func (x *GetUploadAuthReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_note_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadAuthReq.ProtoReflect.Descriptor instead.
func (*GetUploadAuthReq) Descriptor() ([]byte, []int) {
	return file_v1_note_proto_rawDescGZIP(), []int{17}
}

func (x *GetUploadAuthReq) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *GetUploadAuthReq) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *GetUploadAuthReq) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

type UploadAuthResHeaders struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Auth   string `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	Sha256 string `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Date   string `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Token  string `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *UploadAuthResHeaders) Reset() {
	*x = UploadAuthResHeaders{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_note_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadAuthResHeaders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAuthResHeaders) ProtoMessage() {}

func (x *UploadAuthResHeaders) ProtoReflect() protoreflect.Message {
	mi := &file_v1_note_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAuthResHeaders.ProtoReflect.Descriptor instead.
func (*UploadAuthResHeaders) Descriptor() ([]byte, []int) {
	return file_v1_note_proto_rawDescGZIP(), []int{18}
}

func (x *UploadAuthResHeaders) GetAuth() string {
	if x != nil {
		return x.Auth
	}
	return ""
}

func (x *UploadAuthResHeaders) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *UploadAuthResHeaders) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *UploadAuthResHeaders) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetUploadAuthRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileId      string                `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	CurrentTime int64                 `protobuf:"varint,2,opt,name=current_time,json=currentTime,proto3" json:"current_time,omitempty"`
	ExpireTime  int64                 `protobuf:"varint,3,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	UploadAddr  string                `protobuf:"bytes,4,opt,name=upload_addr,json=uploadAddr,proto3" json:"upload_addr,omitempty"`
	Headers     *UploadAuthResHeaders `protobuf:"bytes,5,opt,name=headers,proto3" json:"headers,omitempty"`
}

func (x *GetUploadAuthRes) Reset() {
	*x = GetUploadAuthRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_note_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUploadAuthRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadAuthRes) ProtoMessage() {}

func (x *GetUploadAuthRes) ProtoReflect() protoreflect.Message {
	mi := &file_v1_note_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadAuthRes.ProtoReflect.Descriptor instead.
func (*GetUploadAuthRes) Descriptor() ([]byte, []int) {
	return file_v1_note_proto_rawDescGZIP(), []int{19}
}

func (x *GetUploadAuthRes) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *GetUploadAuthRes) GetCurrentTime() int64 {
	if x != nil {
		return x.CurrentTime
	}
	return 0
}

func (x *GetUploadAuthRes) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *GetUploadAuthRes) GetUploadAddr() string {
	if x != nil {
		return x.UploadAddr
	}
	return ""
}

func (x *GetUploadAuthRes) GetHeaders() *UploadAuthResHeaders {
	if x != nil {
		return x.Headers
	}
	return nil
}

var File_v1_note_proto protoreflect.FileDescriptor

var file_v1_note_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x76, 0x31, 0x2f, 0x6e, 0x6f, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0b, 0x6e, 0x6f, 0x74, 0x65, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x76, 0x31, 0x22, 0x3d, 0x0a, 0x10,
	0x49, 0x73, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x77, 0x6e, 0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x6e, 0x6f, 0x74, 0x65, 0x49, 0x64, 0x22, 0x3c, 0x0a, 0x10, 0x49,
	0x73, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x77, 0x6e, 0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x29, 0x0a, 0x0e, 0x49, 0x73, 0x4e,
	0x6f, 0x74, 0x65, 0x45, 0x78, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x6e,
	0x6f, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6e, 0x6f,
	0x74, 0x65, 0x49, 0x64, 0x22, 0x26, 0x0a, 0x0e, 0x49, 0x73, 0x4e, 0x6f, 0x74, 0x65, 0x45, 0x78,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x78, 0x69, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x65, 0x78, 0x69, 0x73, 0x74, 0x22, 0x54, 0x0a, 0x0e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x42, 0x61, 0x73, 0x69, 0x63, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x69, 0x76,
	0x61, 0x63, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x63, 0x79, 0x22, 0x29, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x77, 0x0a,
	0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x31,
	0x0a, 0x05, 0x62, 0x61, 0x73, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x6e, 0x6f, 0x74, 0x65, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x05, 0x62, 0x61, 0x73, 0x69,
	0x63, 0x12, 0x33, 0x0a, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x6e, 0x6f, 0x74, 0x65, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x06,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x22, 0x28, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x74, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6e, 0x6f, 0x74, 0x65, 0x49, 0x64,
	0x22, 0x28, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x6e, 0x6f, 0x74, 0x65, 0x49, 0x64, 0x22, 0x0f, 0x0a, 0x0d, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x22, 0x58, 0x0a, 0x0d, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07,
	0x6e, 0x6f, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6e,
	0x6f, 0x74, 0x65, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6e, 0x6f, 0x74, 0x65, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x52,
	0x04, 0x6e, 0x6f, 0x74, 0x65, 0x22, 0x28, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e,
	0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x74, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6e, 0x6f, 0x74, 0x65, 0x49, 0x64, 0x22,
	0x25, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a,
	0x07, 0x6e, 0x6f, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06,
	0x6e, 0x6f, 0x74, 0x65, 0x49, 0x64, 0x22, 0x37, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22,
	0xd7, 0x01, 0x0a, 0x08, 0x4e, 0x6f, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x17, 0x0a, 0x07,
	0x6e, 0x6f, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6e,
	0x6f, 0x74, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x65, 0x73, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12,
	0x18, 0x0a, 0x07, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x41, 0x74, 0x12, 0x34, 0x0a, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x18, 0x07, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6e, 0x6f, 0x74, 0x65, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x52, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x22, 0x0d, 0x0a, 0x0b, 0x4c, 0x69, 0x73,
	0x74, 0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x22, 0x3a, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74,
	0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6e, 0x6f, 0x74, 0x65, 0x2e, 0x73, 0x64,
	0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x6f, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x22, 0x63, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x6d, 0x69, 0x6d, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6d, 0x69, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x6c, 0x0a, 0x14, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x75, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x61, 0x75, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x68, 0x61, 0x32, 0x35, 0x36, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x68, 0x61, 0x32, 0x35, 0x36, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0xcd, 0x01, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x12, 0x17, 0x0a, 0x07,
	0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66,
	0x69, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x78, 0x70, 0x69,
	0x72, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x65,
	0x78, 0x70, 0x69, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x64, 0x64, 0x72, 0x12, 0x3b, 0x0a, 0x07, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6e, 0x6f,
	0x74, 0x65, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x52, 0x07,
	0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x32, 0xba, 0x04, 0x0a, 0x04, 0x4e, 0x6f, 0x74, 0x65,
	0x12, 0x4d, 0x0a, 0x0d, 0x49, 0x73, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x77, 0x6e, 0x4e, 0x6f, 0x74,
	0x65, 0x12, 0x1d, 0x2e, 0x6e, 0x6f, 0x74, 0x65, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x76, 0x31, 0x2e,
	0x49, 0x73, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x77, 0x6e, 0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x1a, 0x1d, 0x2e, 0x6e, 0x6f, 0x74, 0x65, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x49,
	0x73, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x77, 0x6e, 0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x12,
	0x47, 0x0a, 0x0b, 0x49, 0x73, 0x4e, 0x6f, 0x74, 0x65, 0x45, 0x78, 0x69, 0x73, 0x74, 0x12, 0x1b,
	0x2e, 0x6e, 0x6f, 0x74, 0x65, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x73, 0x4e,
	0x6f, 0x74, 0x65, 0x45, 0x78, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x6e, 0x6f,
	0x74, 0x65, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x73, 0x4e, 0x6f, 0x74, 0x65,
	0x45, 0x78, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x44, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x12, 0x1a, 0x2e, 0x6e, 0x6f, 0x74, 0x65, 0x2e, 0x73, 0x64,
	0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x6e, 0x6f, 0x74, 0x65, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x12, 0x44,
	0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x12, 0x1a, 0x2e, 0x6e,
	0x6f, 0x74, 0x65, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x6e, 0x6f, 0x74, 0x65, 0x2e,
	0x73, 0x64, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x12, 0x44, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x6f,
	0x74, 0x65, 0x12, 0x1a, 0x2e, 0x6e, 0x6f, 0x74, 0x65, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1a,
	0x2e, 0x6e, 0x6f, 0x74, 0x65, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x12, 0x39, 0x0a, 0x07, 0x47, 0x65,
	0x74, 0x4e, 0x6f, 0x74, 0x65, 0x12, 0x17, 0x2e, 0x6e, 0x6f, 0x74, 0x65, 0x2e, 0x73, 0x64, 0x6b,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x15,
	0x2e, 0x6e, 0x6f, 0x74, 0x65, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x6f, 0x74,
	0x65, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x3e, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x6f, 0x74,
	0x65, 0x12, 0x18, 0x2e, 0x6e, 0x6f, 0x74, 0x65, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x76, 0x31, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x6e, 0x6f,
	0x74, 0x65, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x6f,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x12, 0x4d, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x41, 0x75, 0x74, 0x68, 0x12, 0x1d, 0x2e, 0x6e, 0x6f, 0x74, 0x65, 0x2e, 0x73, 0x64,
	0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x75,
	0x74, 0x68, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x6e, 0x6f, 0x74, 0x65, 0x2e, 0x73, 0x64, 0x6b,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x75, 0x74,
	0x68, 0x52, 0x65, 0x73, 0x42, 0x97, 0x01, 0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x2e, 0x6e, 0x6f, 0x74,
	0x65, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x76, 0x31, 0x42, 0x09, 0x4e, 0x6f, 0x74, 0x65, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x72, 0x79, 0x61, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x2f,
	0x77, 0x68, 0x69, 0x6d, 0x65, 0x72, 0x2f, 0x6e, 0x6f, 0x74, 0x65, 0x2f, 0x73, 0x64, 0x6b, 0x2f,
	0x76, 0x31, 0xa2, 0x02, 0x03, 0x4e, 0x53, 0x58, 0xaa, 0x02, 0x0b, 0x4e, 0x6f, 0x74, 0x65, 0x2e,
	0x53, 0x64, 0x6b, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x0b, 0x4e, 0x6f, 0x74, 0x65, 0x5c, 0x53, 0x64,
	0x6b, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x17, 0x4e, 0x6f, 0x74, 0x65, 0x5c, 0x53, 0x64, 0x6b, 0x5c,
	0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02,
	0x0d, 0x4e, 0x6f, 0x74, 0x65, 0x3a, 0x3a, 0x53, 0x64, 0x6b, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_note_proto_rawDescOnce sync.Once
	file_v1_note_proto_rawDescData = file_v1_note_proto_rawDesc
)

func file_v1_note_proto_rawDescGZIP() []byte {
	file_v1_note_proto_rawDescOnce.Do(func() {
		file_v1_note_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_note_proto_rawDescData)
	})
	return file_v1_note_proto_rawDescData
}

var file_v1_note_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_v1_note_proto_goTypes = []any{
	(*IsUserOwnNoteReq)(nil),     // 0: note.sdk.v1.IsUserOwnNoteReq
	(*IsUserOwnNoteRes)(nil),     // 1: note.sdk.v1.IsUserOwnNoteRes
	(*IsNoteExistReq)(nil),       // 2: note.sdk.v1.IsNoteExistReq
	(*IsNoteExistRes)(nil),       // 3: note.sdk.v1.IsNoteExistRes
	(*CreateReqBasic)(nil),       // 4: note.sdk.v1.CreateReqBasic
	(*CreateReqImage)(nil),       // 5: note.sdk.v1.CreateReqImage
	(*CreateNoteReq)(nil),        // 6: note.sdk.v1.CreateNoteReq
	(*CreateNoteRes)(nil),        // 7: note.sdk.v1.CreateNoteRes
	(*DeleteNoteReq)(nil),        // 8: note.sdk.v1.DeleteNoteReq
	(*DeleteNoteRes)(nil),        // 9: note.sdk.v1.DeleteNoteRes
	(*UpdateNoteReq)(nil),        // 10: note.sdk.v1.UpdateNoteReq
	(*UpdateNoteRes)(nil),        // 11: note.sdk.v1.UpdateNoteRes
	(*GetNoteReq)(nil),           // 12: note.sdk.v1.GetNoteReq
	(*GetNoteResImage)(nil),      // 13: note.sdk.v1.GetNoteResImage
	(*NoteItem)(nil),             // 14: note.sdk.v1.NoteItem
	(*ListNoteReq)(nil),          // 15: note.sdk.v1.ListNoteReq
	(*ListNoteRes)(nil),          // 16: note.sdk.v1.ListNoteRes
	(*GetUploadAuthReq)(nil),     // 17: note.sdk.v1.GetUploadAuthReq
	(*UploadAuthResHeaders)(nil), // 18: note.sdk.v1.UploadAuthResHeaders
	(*GetUploadAuthRes)(nil),     // 19: note.sdk.v1.GetUploadAuthRes
}
var file_v1_note_proto_depIdxs = []int32{
	4,  // 0: note.sdk.v1.CreateNoteReq.basic:type_name -> note.sdk.v1.CreateReqBasic
	5,  // 1: note.sdk.v1.CreateNoteReq.images:type_name -> note.sdk.v1.CreateReqImage
	6,  // 2: note.sdk.v1.UpdateNoteReq.note:type_name -> note.sdk.v1.CreateNoteReq
	13, // 3: note.sdk.v1.NoteItem.images:type_name -> note.sdk.v1.GetNoteResImage
	14, // 4: note.sdk.v1.ListNoteRes.items:type_name -> note.sdk.v1.NoteItem
	18, // 5: note.sdk.v1.GetUploadAuthRes.headers:type_name -> note.sdk.v1.UploadAuthResHeaders
	0,  // 6: note.sdk.v1.Note.IsUserOwnNote:input_type -> note.sdk.v1.IsUserOwnNoteReq
	2,  // 7: note.sdk.v1.Note.IsNoteExist:input_type -> note.sdk.v1.IsNoteExistReq
	6,  // 8: note.sdk.v1.Note.CreateNote:input_type -> note.sdk.v1.CreateNoteReq
	10, // 9: note.sdk.v1.Note.UpdateNote:input_type -> note.sdk.v1.UpdateNoteReq
	8,  // 10: note.sdk.v1.Note.DeleteNote:input_type -> note.sdk.v1.DeleteNoteReq
	12, // 11: note.sdk.v1.Note.GetNote:input_type -> note.sdk.v1.GetNoteReq
	15, // 12: note.sdk.v1.Note.ListNote:input_type -> note.sdk.v1.ListNoteReq
	17, // 13: note.sdk.v1.Note.GetUploadAuth:input_type -> note.sdk.v1.GetUploadAuthReq
	1,  // 14: note.sdk.v1.Note.IsUserOwnNote:output_type -> note.sdk.v1.IsUserOwnNoteRes
	3,  // 15: note.sdk.v1.Note.IsNoteExist:output_type -> note.sdk.v1.IsNoteExistRes
	7,  // 16: note.sdk.v1.Note.CreateNote:output_type -> note.sdk.v1.CreateNoteRes
	11, // 17: note.sdk.v1.Note.UpdateNote:output_type -> note.sdk.v1.UpdateNoteRes
	9,  // 18: note.sdk.v1.Note.DeleteNote:output_type -> note.sdk.v1.DeleteNoteRes
	14, // 19: note.sdk.v1.Note.GetNote:output_type -> note.sdk.v1.NoteItem
	16, // 20: note.sdk.v1.Note.ListNote:output_type -> note.sdk.v1.ListNoteRes
	19, // 21: note.sdk.v1.Note.GetUploadAuth:output_type -> note.sdk.v1.GetUploadAuthRes
	14, // [14:22] is the sub-list for method output_type
	6,  // [6:14] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_v1_note_proto_init() }
func file_v1_note_proto_init() {
	if File_v1_note_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_note_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*IsUserOwnNoteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_note_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*IsUserOwnNoteRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_note_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*IsNoteExistReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_note_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*IsNoteExistRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_note_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*CreateReqBasic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_note_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*CreateReqImage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_note_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*CreateNoteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_note_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*CreateNoteRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_note_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteNoteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_note_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteNoteRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_note_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateNoteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_note_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateNoteRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_note_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*GetNoteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_note_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*GetNoteResImage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_note_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*NoteItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_note_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*ListNoteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_note_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*ListNoteRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_note_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*GetUploadAuthReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_note_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*UploadAuthResHeaders); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_note_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*GetUploadAuthRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_note_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_note_proto_goTypes,
		DependencyIndexes: file_v1_note_proto_depIdxs,
		MessageInfos:      file_v1_note_proto_msgTypes,
	}.Build()
	File_v1_note_proto = out.File
	file_v1_note_proto_rawDesc = nil
	file_v1_note_proto_goTypes = nil
	file_v1_note_proto_depIdxs = nil
}
