// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: v1/noteinteract.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LikeNoteRequest_Operation int32

const (
	LikeNoteRequest_OPERATION_UNDO_LIKE LikeNoteRequest_Operation = 0 // 取消点赞
	LikeNoteRequest_OPERATION_DO_LIKE   LikeNoteRequest_Operation = 1 // 点赞
)

// Enum value maps for LikeNoteRequest_Operation.
var (
	LikeNoteRequest_Operation_name = map[int32]string{
		0: "OPERATION_UNDO_LIKE",
		1: "OPERATION_DO_LIKE",
	}
	LikeNoteRequest_Operation_value = map[string]int32{
		"OPERATION_UNDO_LIKE": 0,
		"OPERATION_DO_LIKE":   1,
	}
)

func (x LikeNoteRequest_Operation) Enum() *LikeNoteRequest_Operation {
	p := new(LikeNoteRequest_Operation)
	*p = x
	return p
}

func (x LikeNoteRequest_Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LikeNoteRequest_Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_noteinteract_proto_enumTypes[0].Descriptor()
}

func (LikeNoteRequest_Operation) Type() protoreflect.EnumType {
	return &file_v1_noteinteract_proto_enumTypes[0]
}

func (x LikeNoteRequest_Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LikeNoteRequest_Operation.Descriptor instead.
func (LikeNoteRequest_Operation) EnumDescriptor() ([]byte, []int) {
	return file_v1_noteinteract_proto_rawDescGZIP(), []int{0, 0}
}

type LikeNoteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NoteId    uint64                    `protobuf:"varint,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"` // 笔记id
	Uid       uint64                    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`                     // 执行点赞的用户id
	Operation LikeNoteRequest_Operation `protobuf:"varint,3,opt,name=operation,proto3,enum=note.sdk.v1.LikeNoteRequest_Operation" json:"operation,omitempty"`
}

func (x *LikeNoteRequest) Reset() {
	*x = LikeNoteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_noteinteract_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LikeNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeNoteRequest) ProtoMessage() {}

func (x *LikeNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_noteinteract_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeNoteRequest.ProtoReflect.Descriptor instead.
func (*LikeNoteRequest) Descriptor() ([]byte, []int) {
	return file_v1_noteinteract_proto_rawDescGZIP(), []int{0}
}

func (x *LikeNoteRequest) GetNoteId() uint64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

func (x *LikeNoteRequest) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *LikeNoteRequest) GetOperation() LikeNoteRequest_Operation {
	if x != nil {
		return x.Operation
	}
	return LikeNoteRequest_OPERATION_UNDO_LIKE
}

type LikeNoteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LikeNoteResponse) Reset() {
	*x = LikeNoteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_noteinteract_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LikeNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeNoteResponse) ProtoMessage() {}

func (x *LikeNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_noteinteract_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeNoteResponse.ProtoReflect.Descriptor instead.
func (*LikeNoteResponse) Descriptor() ([]byte, []int) {
	return file_v1_noteinteract_proto_rawDescGZIP(), []int{1}
}

type GetNoteLikesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NoteId uint64 `protobuf:"varint,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"` //笔记id
}

func (x *GetNoteLikesRequest) Reset() {
	*x = GetNoteLikesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_noteinteract_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNoteLikesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNoteLikesRequest) ProtoMessage() {}

func (x *GetNoteLikesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_noteinteract_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNoteLikesRequest.ProtoReflect.Descriptor instead.
func (*GetNoteLikesRequest) Descriptor() ([]byte, []int) {
	return file_v1_noteinteract_proto_rawDescGZIP(), []int{2}
}

func (x *GetNoteLikesRequest) GetNoteId() uint64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

type GetNoteLikesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NoteId uint64 `protobuf:"varint,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	Likes  uint64 `protobuf:"varint,2,opt,name=likes,proto3" json:"likes,omitempty"` // 点赞数量
}

func (x *GetNoteLikesResponse) Reset() {
	*x = GetNoteLikesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_noteinteract_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNoteLikesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNoteLikesResponse) ProtoMessage() {}

func (x *GetNoteLikesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_noteinteract_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNoteLikesResponse.ProtoReflect.Descriptor instead.
func (*GetNoteLikesResponse) Descriptor() ([]byte, []int) {
	return file_v1_noteinteract_proto_rawDescGZIP(), []int{3}
}

func (x *GetNoteLikesResponse) GetNoteId() uint64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

func (x *GetNoteLikesResponse) GetLikes() uint64 {
	if x != nil {
		return x.Likes
	}
	return 0
}

var File_v1_noteinteract_proto protoreflect.FileDescriptor

var file_v1_noteinteract_proto_rawDesc = []byte{
	0x0a, 0x15, 0x76, 0x31, 0x2f, 0x6e, 0x6f, 0x74, 0x65, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6e, 0x6f, 0x74, 0x65, 0x2e, 0x73, 0x64,
	0x6b, 0x2e, 0x76, 0x31, 0x1a, 0x1b, 0x62, 0x75, 0x66, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x0d, 0x76, 0x31, 0x2f, 0x6e, 0x6f, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xd1, 0x01, 0x0a, 0x0f, 0x4c, 0x69, 0x6b, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x07, 0x6e, 0x6f, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x07, 0xba, 0x48, 0x04, 0x32, 0x02, 0x20, 0x00, 0x52, 0x06,
	0x6e, 0x6f, 0x74, 0x65, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x42, 0x07, 0xba, 0x48, 0x04, 0x32, 0x02, 0x20, 0x00, 0x52, 0x03, 0x75, 0x69,
	0x64, 0x12, 0x44, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x26, 0x2e, 0x6e, 0x6f, 0x74, 0x65, 0x2e, 0x73, 0x64, 0x6b, 0x2e,
	0x76, 0x31, 0x2e, 0x4c, 0x69, 0x6b, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x6f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x3b, 0x0a, 0x09, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x13, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x49, 0x4f,
	0x4e, 0x5f, 0x55, 0x4e, 0x44, 0x4f, 0x5f, 0x4c, 0x49, 0x4b, 0x45, 0x10, 0x00, 0x12, 0x15, 0x0a,
	0x11, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x44, 0x4f, 0x5f, 0x4c, 0x49,
	0x4b, 0x45, 0x10, 0x01, 0x22, 0x12, 0x0a, 0x10, 0x4c, 0x69, 0x6b, 0x65, 0x4e, 0x6f, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x37, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4e,
	0x6f, 0x74, 0x65, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x20, 0x0a, 0x07, 0x6e, 0x6f, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x42, 0x07, 0xba, 0x48, 0x04, 0x32, 0x02, 0x20, 0x00, 0x52, 0x06, 0x6e, 0x6f, 0x74, 0x65, 0x49,
	0x64, 0x22, 0x45, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x4c, 0x69, 0x6b, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x74,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6e, 0x6f, 0x74, 0x65,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x05, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x32, 0xb3, 0x01, 0x0a, 0x13, 0x4e, 0x6f, 0x74,
	0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x47, 0x0a, 0x08, 0x4c, 0x69, 0x6b, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x12, 0x1c, 0x2e, 0x6e,
	0x6f, 0x74, 0x65, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x6b, 0x65, 0x4e,
	0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x6e, 0x6f, 0x74,
	0x65, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x6b, 0x65, 0x4e, 0x6f, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x0c, 0x47, 0x65, 0x74,
	0x4e, 0x6f, 0x74, 0x65, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x12, 0x20, 0x2e, 0x6e, 0x6f, 0x74, 0x65,
	0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x4c,
	0x69, 0x6b, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x6e, 0x6f,
	0x74, 0x65, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x74,
	0x65, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x9f,
	0x01, 0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x2e, 0x6e, 0x6f, 0x74, 0x65, 0x2e, 0x73, 0x64, 0x6b, 0x2e,
	0x76, 0x31, 0x42, 0x11, 0x4e, 0x6f, 0x74, 0x65, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x79, 0x61, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x62, 0x6f, 0x6f, 0x6b,
	0x73, 0x2f, 0x77, 0x68, 0x69, 0x6d, 0x65, 0x72, 0x2f, 0x6e, 0x6f, 0x74, 0x65, 0x2f, 0x73, 0x64,
	0x6b, 0x2f, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x4e, 0x53, 0x58, 0xaa, 0x02, 0x0b, 0x4e, 0x6f, 0x74,
	0x65, 0x2e, 0x53, 0x64, 0x6b, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x0b, 0x4e, 0x6f, 0x74, 0x65, 0x5c,
	0x53, 0x64, 0x6b, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x17, 0x4e, 0x6f, 0x74, 0x65, 0x5c, 0x53, 0x64,
	0x6b, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0xea, 0x02, 0x0d, 0x4e, 0x6f, 0x74, 0x65, 0x3a, 0x3a, 0x53, 0x64, 0x6b, 0x3a, 0x3a, 0x56, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_noteinteract_proto_rawDescOnce sync.Once
	file_v1_noteinteract_proto_rawDescData = file_v1_noteinteract_proto_rawDesc
)

func file_v1_noteinteract_proto_rawDescGZIP() []byte {
	file_v1_noteinteract_proto_rawDescOnce.Do(func() {
		file_v1_noteinteract_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_noteinteract_proto_rawDescData)
	})
	return file_v1_noteinteract_proto_rawDescData
}

var file_v1_noteinteract_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_noteinteract_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_v1_noteinteract_proto_goTypes = []any{
	(LikeNoteRequest_Operation)(0), // 0: note.sdk.v1.LikeNoteRequest.Operation
	(*LikeNoteRequest)(nil),        // 1: note.sdk.v1.LikeNoteRequest
	(*LikeNoteResponse)(nil),       // 2: note.sdk.v1.LikeNoteResponse
	(*GetNoteLikesRequest)(nil),    // 3: note.sdk.v1.GetNoteLikesRequest
	(*GetNoteLikesResponse)(nil),   // 4: note.sdk.v1.GetNoteLikesResponse
}
var file_v1_noteinteract_proto_depIdxs = []int32{
	0, // 0: note.sdk.v1.LikeNoteRequest.operation:type_name -> note.sdk.v1.LikeNoteRequest.Operation
	1, // 1: note.sdk.v1.NoteInteractService.LikeNote:input_type -> note.sdk.v1.LikeNoteRequest
	3, // 2: note.sdk.v1.NoteInteractService.GetNoteLikes:input_type -> note.sdk.v1.GetNoteLikesRequest
	2, // 3: note.sdk.v1.NoteInteractService.LikeNote:output_type -> note.sdk.v1.LikeNoteResponse
	4, // 4: note.sdk.v1.NoteInteractService.GetNoteLikes:output_type -> note.sdk.v1.GetNoteLikesResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_noteinteract_proto_init() }
func file_v1_noteinteract_proto_init() {
	if File_v1_noteinteract_proto != nil {
		return
	}
	file_v1_note_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_v1_noteinteract_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*LikeNoteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_noteinteract_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*LikeNoteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_noteinteract_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetNoteLikesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_noteinteract_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetNoteLikesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_noteinteract_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_noteinteract_proto_goTypes,
		DependencyIndexes: file_v1_noteinteract_proto_depIdxs,
		EnumInfos:         file_v1_noteinteract_proto_enumTypes,
		MessageInfos:      file_v1_noteinteract_proto_msgTypes,
	}.Build()
	File_v1_noteinteract_proto = out.File
	file_v1_noteinteract_proto_rawDesc = nil
	file_v1_noteinteract_proto_goTypes = nil
	file_v1_noteinteract_proto_depIdxs = nil
}
