// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.0
// source: note.proto

package sdk

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IsUserOwnNoteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid     uint64   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`                               // 用户id
	NoteIds []uint64 `protobuf:"varint,2,rep,packed,name=note_ids,json=noteIds,proto3" json:"note_ids,omitempty"` // 笔记id
}

func (x *IsUserOwnNoteReq) Reset() {
	*x = IsUserOwnNoteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_note_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsUserOwnNoteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsUserOwnNoteReq) ProtoMessage() {}

func (x *IsUserOwnNoteReq) ProtoReflect() protoreflect.Message {
	mi := &file_note_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsUserOwnNoteReq.ProtoReflect.Descriptor instead.
func (*IsUserOwnNoteReq) Descriptor() ([]byte, []int) {
	return file_note_proto_rawDescGZIP(), []int{0}
}

func (x *IsUserOwnNoteReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *IsUserOwnNoteReq) GetNoteIds() []uint64 {
	if x != nil {
		return x.NoteIds
	}
	return nil
}

type IsUserOwnNoteRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid    uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Result []bool `protobuf:"varint,2,rep,packed,name=result,proto3" json:"result,omitempty"` // 结果
}

func (x *IsUserOwnNoteRes) Reset() {
	*x = IsUserOwnNoteRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_note_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsUserOwnNoteRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsUserOwnNoteRes) ProtoMessage() {}

func (x *IsUserOwnNoteRes) ProtoReflect() protoreflect.Message {
	mi := &file_note_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsUserOwnNoteRes.ProtoReflect.Descriptor instead.
func (*IsUserOwnNoteRes) Descriptor() ([]byte, []int) {
	return file_note_proto_rawDescGZIP(), []int{1}
}

func (x *IsUserOwnNoteRes) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *IsUserOwnNoteRes) GetResult() []bool {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_note_proto protoreflect.FileDescriptor

var file_note_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6e, 0x6f, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6e, 0x6f,
	0x74, 0x65, 0x2e, 0x76, 0x31, 0x22, 0x3f, 0x0a, 0x10, 0x49, 0x73, 0x55, 0x73, 0x65, 0x72, 0x4f,
	0x77, 0x6e, 0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6e,
	0x6f, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x04, 0x52, 0x07, 0x6e,
	0x6f, 0x74, 0x65, 0x49, 0x64, 0x73, 0x22, 0x3c, 0x0a, 0x10, 0x49, 0x73, 0x55, 0x73, 0x65, 0x72,
	0x4f, 0x77, 0x6e, 0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x32, 0x4d, 0x0a, 0x04, 0x4e, 0x6f, 0x74, 0x65, 0x12, 0x45, 0x0a, 0x0d,
	0x49, 0x73, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x77, 0x6e, 0x4e, 0x6f, 0x74, 0x65, 0x12, 0x19, 0x2e,
	0x6e, 0x6f, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x73, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x77,
	0x6e, 0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x6e, 0x6f, 0x74, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x49, 0x73, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x77, 0x6e, 0x4e, 0x6f, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x73, 0x64, 0x6b, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_note_proto_rawDescOnce sync.Once
	file_note_proto_rawDescData = file_note_proto_rawDesc
)

func file_note_proto_rawDescGZIP() []byte {
	file_note_proto_rawDescOnce.Do(func() {
		file_note_proto_rawDescData = protoimpl.X.CompressGZIP(file_note_proto_rawDescData)
	})
	return file_note_proto_rawDescData
}

var file_note_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_note_proto_goTypes = []interface{}{
	(*IsUserOwnNoteReq)(nil), // 0: note.v1.IsUserOwnNoteReq
	(*IsUserOwnNoteRes)(nil), // 1: note.v1.IsUserOwnNoteRes
}
var file_note_proto_depIdxs = []int32{
	0, // 0: note.v1.Note.IsUserOwnNote:input_type -> note.v1.IsUserOwnNoteReq
	1, // 1: note.v1.Note.IsUserOwnNote:output_type -> note.v1.IsUserOwnNoteRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_note_proto_init() }
func file_note_proto_init() {
	if File_note_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_note_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsUserOwnNoteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_note_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsUserOwnNoteRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_note_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_note_proto_goTypes,
		DependencyIndexes: file_note_proto_depIdxs,
		MessageInfos:      file_note_proto_msgTypes,
	}.Build()
	File_note_proto = out.File
	file_note_proto_rawDesc = nil
	file_note_proto_goTypes = nil
	file_note_proto_depIdxs = nil
}
