// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.0
// source: reply.proto

package sdk

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SortType int32

const (
	SortType_ByTime  SortType = 0 // 按照发布时间排序
	SortType_ByTrend SortType = 1 // 按照热度排序
)

// Enum value maps for SortType.
var (
	SortType_name = map[int32]string{
		0: "ByTime",
		1: "ByTrend",
	}
	SortType_value = map[string]int32{
		"ByTime":  0,
		"ByTrend": 1,
	}
)

func (x SortType) Enum() *SortType {
	p := new(SortType)
	*p = x
	return p
}

func (x SortType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortType) Descriptor() protoreflect.EnumDescriptor {
	return file_reply_proto_enumTypes[0].Descriptor()
}

func (SortType) Type() protoreflect.EnumType {
	return &file_reply_proto_enumTypes[0]
}

func (x SortType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortType.Descriptor instead.
func (SortType) EnumDescriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{0}
}

// 发布评论
type AddReplyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReplyType uint32 `protobuf:"varint,1,opt,name=reply_type,json=replyType,proto3" json:"reply_type,omitempty"` // 评论类型
	Oid       uint64 `protobuf:"varint,2,opt,name=oid,proto3" json:"oid,omitempty"`                              // 被评论对象id
	Content   string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                       // 评论内容
	RootId    uint64 `protobuf:"varint,4,opt,name=root_id,json=rootId,proto3" json:"root_id,omitempty"`          // 根评论id
	ParentId  uint64 `protobuf:"varint,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`    // 被回复的评论id
	ReplyUid  uint64 `protobuf:"varint,6,opt,name=reply_uid,json=replyUid,proto3" json:"reply_uid,omitempty"`    // 被回复的用户id
}

func (x *AddReplyReq) Reset() {
	*x = AddReplyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reply_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddReplyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReplyReq) ProtoMessage() {}

func (x *AddReplyReq) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReplyReq.ProtoReflect.Descriptor instead.
func (*AddReplyReq) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{0}
}

func (x *AddReplyReq) GetReplyType() uint32 {
	if x != nil {
		return x.ReplyType
	}
	return 0
}

func (x *AddReplyReq) GetOid() uint64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

func (x *AddReplyReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AddReplyReq) GetRootId() uint64 {
	if x != nil {
		return x.RootId
	}
	return 0
}

func (x *AddReplyReq) GetParentId() uint64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *AddReplyReq) GetReplyUid() uint64 {
	if x != nil {
		return x.ReplyUid
	}
	return 0
}

type AddReplyRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReplyId uint64 `protobuf:"varint,1,opt,name=reply_id,json=replyId,proto3" json:"reply_id,omitempty"` // 评论id
}

func (x *AddReplyRes) Reset() {
	*x = AddReplyRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reply_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddReplyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReplyRes) ProtoMessage() {}

func (x *AddReplyRes) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReplyRes.ProtoReflect.Descriptor instead.
func (*AddReplyRes) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{1}
}

func (x *AddReplyRes) GetReplyId() uint64 {
	if x != nil {
		return x.ReplyId
	}
	return 0
}

// 删除评论
type DelReplyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReplyId uint64 `protobuf:"varint,1,opt,name=reply_id,json=replyId,proto3" json:"reply_id,omitempty"` // 评论id
}

func (x *DelReplyReq) Reset() {
	*x = DelReplyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reply_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelReplyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelReplyReq) ProtoMessage() {}

func (x *DelReplyReq) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelReplyReq.ProtoReflect.Descriptor instead.
func (*DelReplyReq) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{2}
}

func (x *DelReplyReq) GetReplyId() uint64 {
	if x != nil {
		return x.ReplyId
	}
	return 0
}

type DelReplyRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DelReplyRes) Reset() {
	*x = DelReplyRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reply_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelReplyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelReplyRes) ProtoMessage() {}

func (x *DelReplyRes) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelReplyRes.ProtoReflect.Descriptor instead.
func (*DelReplyRes) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{3}
}

// 点赞/取消点赞
type LikeActionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LikeActionReq) Reset() {
	*x = LikeActionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reply_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LikeActionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeActionReq) ProtoMessage() {}

func (x *LikeActionReq) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeActionReq.ProtoReflect.Descriptor instead.
func (*LikeActionReq) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{4}
}

type LikeActionRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LikeActionRes) Reset() {
	*x = LikeActionRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reply_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LikeActionRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeActionRes) ProtoMessage() {}

func (x *LikeActionRes) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeActionRes.ProtoReflect.Descriptor instead.
func (*LikeActionRes) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{5}
}

// 点踩/取消点踩
type DislikeActionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DislikeActionReq) Reset() {
	*x = DislikeActionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reply_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DislikeActionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DislikeActionReq) ProtoMessage() {}

func (x *DislikeActionReq) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DislikeActionReq.ProtoReflect.Descriptor instead.
func (*DislikeActionReq) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{6}
}

type DislikeActionRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DislikeActionRes) Reset() {
	*x = DislikeActionRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reply_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DislikeActionRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DislikeActionRes) ProtoMessage() {}

func (x *DislikeActionRes) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DislikeActionRes.ProtoReflect.Descriptor instead.
func (*DislikeActionRes) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{7}
}

// 举报
type ReportReplyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReportReplyReq) Reset() {
	*x = ReportReplyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reply_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportReplyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportReplyReq) ProtoMessage() {}

func (x *ReportReplyReq) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportReplyReq.ProtoReflect.Descriptor instead.
func (*ReportReplyReq) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{8}
}

type ReportReplyRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReportReplyRes) Reset() {
	*x = ReportReplyRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reply_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportReplyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportReplyRes) ProtoMessage() {}

func (x *ReportReplyRes) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportReplyRes.ProtoReflect.Descriptor instead.
func (*ReportReplyRes) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{9}
}

// 置顶
type PinReplyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PinReplyReq) Reset() {
	*x = PinReplyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reply_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PinReplyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinReplyReq) ProtoMessage() {}

func (x *PinReplyReq) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinReplyReq.ProtoReflect.Descriptor instead.
func (*PinReplyReq) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{10}
}

type PinReplyRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PinReplyRes) Reset() {
	*x = PinReplyRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reply_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PinReplyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinReplyRes) ProtoMessage() {}

func (x *PinReplyRes) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinReplyRes.ProtoReflect.Descriptor instead.
func (*PinReplyRes) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{11}
}

// 获取评论
type PageGetReplyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Oid    uint64   `protobuf:"varint,1,opt,name=oid,proto3" json:"oid,omitempty"`
	Cursor uint64   `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`                                        // 起始游标
	SortBy SortType `protobuf:"varint,3,opt,name=sort_by,json=sortBy,proto3,enum=comment.v1.SortType" json:"sort_by,omitempty"` // 排序方式
}

func (x *PageGetReplyReq) Reset() {
	*x = PageGetReplyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reply_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageGetReplyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageGetReplyReq) ProtoMessage() {}

func (x *PageGetReplyReq) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageGetReplyReq.ProtoReflect.Descriptor instead.
func (*PageGetReplyReq) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{12}
}

func (x *PageGetReplyReq) GetOid() uint64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

func (x *PageGetReplyReq) GetCursor() uint64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *PageGetReplyReq) GetSortBy() SortType {
	if x != nil {
		return x.SortBy
	}
	return SortType_ByTime
}

// 评论实体
type ReplyItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                 // 评论id
	Oid       uint64 `protobuf:"varint,2,opt,name=oid,proto3" json:"oid,omitempty"`                               // 被评论对象id
	ReplyType uint32 `protobuf:"varint,3,opt,name=reply_type,json=replyType,proto3" json:"reply_type,omitempty"`  // 评论类型
	Content   string `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`                        // 评论内容
	Uid       uint64 `protobuf:"varint,5,opt,name=uid,proto3" json:"uid,omitempty"`                               // 评论发表用户uid
	RootId    uint64 `protobuf:"varint,6,opt,name=root_id,json=rootId,proto3" json:"root_id,omitempty"`           // 根评论id
	ParentId  uint64 `protobuf:"varint,7,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`     // 父评论id
	Ruid      uint64 `protobuf:"varint,8,opt,name=ruid,proto3" json:"ruid,omitempty"`                             // 被回复的用户id
	LikeCount uint64 `protobuf:"varint,9,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`  // 点赞数
	HateCount uint64 `protobuf:"varint,10,opt,name=hate_count,json=hateCount,proto3" json:"hate_count,omitempty"` // 点踩数
	Ctime     int64  `protobuf:"varint,11,opt,name=ctime,proto3" json:"ctime,omitempty"`                          // 发布时间
	Mtime     int64  `protobuf:"varint,12,opt,name=mtime,proto3" json:"mtime,omitempty"`                          // 修改时间
	Ip        string `protobuf:"bytes,13,opt,name=ip,proto3" json:"ip,omitempty"`                                 // 发布时ip地址
	IsPin     bool   `protobuf:"varint,14,opt,name=is_pin,json=isPin,proto3" json:"is_pin,omitempty"`             // 是否为置顶评论
}

func (x *ReplyItem) Reset() {
	*x = ReplyItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reply_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplyItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyItem) ProtoMessage() {}

func (x *ReplyItem) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyItem.ProtoReflect.Descriptor instead.
func (*ReplyItem) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{13}
}

func (x *ReplyItem) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReplyItem) GetOid() uint64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

func (x *ReplyItem) GetReplyType() uint32 {
	if x != nil {
		return x.ReplyType
	}
	return 0
}

func (x *ReplyItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ReplyItem) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ReplyItem) GetRootId() uint64 {
	if x != nil {
		return x.RootId
	}
	return 0
}

func (x *ReplyItem) GetParentId() uint64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *ReplyItem) GetRuid() uint64 {
	if x != nil {
		return x.Ruid
	}
	return 0
}

func (x *ReplyItem) GetLikeCount() uint64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *ReplyItem) GetHateCount() uint64 {
	if x != nil {
		return x.HateCount
	}
	return 0
}

func (x *ReplyItem) GetCtime() int64 {
	if x != nil {
		return x.Ctime
	}
	return 0
}

func (x *ReplyItem) GetMtime() int64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

func (x *ReplyItem) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ReplyItem) GetIsPin() bool {
	if x != nil {
		return x.IsPin
	}
	return false
}

type PageGetReplyRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Replies    []*ReplyItem `protobuf:"bytes,1,rep,name=replies,proto3" json:"replies,omitempty"`                          // 评论数据
	NextCursor uint64       `protobuf:"varint,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"` // 分页获取下一次请求的游标
	HasNext    bool         `protobuf:"varint,3,opt,name=has_next,json=hasNext,proto3" json:"has_next,omitempty"`          // 是否还有数据
}

func (x *PageGetReplyRes) Reset() {
	*x = PageGetReplyRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reply_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageGetReplyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageGetReplyRes) ProtoMessage() {}

func (x *PageGetReplyRes) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageGetReplyRes.ProtoReflect.Descriptor instead.
func (*PageGetReplyRes) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{14}
}

func (x *PageGetReplyRes) GetReplies() []*ReplyItem {
	if x != nil {
		return x.Replies
	}
	return nil
}

func (x *PageGetReplyRes) GetNextCursor() uint64 {
	if x != nil {
		return x.NextCursor
	}
	return 0
}

func (x *PageGetReplyRes) GetHasNext() bool {
	if x != nil {
		return x.HasNext
	}
	return false
}

type PageGetSubReplyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Oid    uint64   `protobuf:"varint,1,opt,name=oid,proto3" json:"oid,omitempty"`                                              // 被评论对象id
	RootId uint64   `protobuf:"varint,2,opt,name=root_id,json=rootId,proto3" json:"root_id,omitempty"`                          // 主评论id
	Cursor uint64   `protobuf:"varint,3,opt,name=cursor,proto3" json:"cursor,omitempty"`                                        // 起始游标
	SortBy SortType `protobuf:"varint,4,opt,name=sort_by,json=sortBy,proto3,enum=comment.v1.SortType" json:"sort_by,omitempty"` // 排序方式
}

func (x *PageGetSubReplyReq) Reset() {
	*x = PageGetSubReplyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reply_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageGetSubReplyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageGetSubReplyReq) ProtoMessage() {}

func (x *PageGetSubReplyReq) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageGetSubReplyReq.ProtoReflect.Descriptor instead.
func (*PageGetSubReplyReq) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{15}
}

func (x *PageGetSubReplyReq) GetOid() uint64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

func (x *PageGetSubReplyReq) GetRootId() uint64 {
	if x != nil {
		return x.RootId
	}
	return 0
}

func (x *PageGetSubReplyReq) GetCursor() uint64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *PageGetSubReplyReq) GetSortBy() SortType {
	if x != nil {
		return x.SortBy
	}
	return SortType_ByTime
}

type PageGetSubReplyRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Replies    []*ReplyItem `protobuf:"bytes,1,rep,name=replies,proto3" json:"replies,omitempty"`
	NextCursor uint64       `protobuf:"varint,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasNext    bool         `protobuf:"varint,3,opt,name=has_next,json=hasNext,proto3" json:"has_next,omitempty"`
}

func (x *PageGetSubReplyRes) Reset() {
	*x = PageGetSubReplyRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reply_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageGetSubReplyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageGetSubReplyRes) ProtoMessage() {}

func (x *PageGetSubReplyRes) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageGetSubReplyRes.ProtoReflect.Descriptor instead.
func (*PageGetSubReplyRes) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{16}
}

func (x *PageGetSubReplyRes) GetReplies() []*ReplyItem {
	if x != nil {
		return x.Replies
	}
	return nil
}

func (x *PageGetSubReplyRes) GetNextCursor() uint64 {
	if x != nil {
		return x.NextCursor
	}
	return 0
}

func (x *PageGetSubReplyRes) GetHasNext() bool {
	if x != nil {
		return x.HasNext
	}
	return false
}

var File_reply_proto protoreflect.FileDescriptor

var file_reply_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x1a, 0x1b, 0x62, 0x75, 0x66, 0x2f, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xab, 0x01, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x72, 0x65, 0x70, 0x6c,
	0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x03, 0x6f, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x74, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61,
	0x72, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x70,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x70, 0x6c, 0x79,
	0x5f, 0x75, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x72, 0x65, 0x70, 0x6c,
	0x79, 0x55, 0x69, 0x64, 0x22, 0x28, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x52, 0x65, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x49, 0x64, 0x22, 0x28,
	0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a,
	0x08, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x07, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x49, 0x64, 0x22, 0x0d, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x73, 0x22, 0x0f, 0x0a, 0x0d, 0x4c, 0x69, 0x6b, 0x65, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x22, 0x0f, 0x0a, 0x0d, 0x4c, 0x69, 0x6b, 0x65,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x22, 0x12, 0x0a, 0x10, 0x44, 0x69, 0x73,
	0x6c, 0x69, 0x6b, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x22, 0x12, 0x0a,
	0x10, 0x44, 0x69, 0x73, 0x6c, 0x69, 0x6b, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x22, 0x10, 0x0a, 0x0e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x52, 0x65, 0x71, 0x22, 0x10, 0x0a, 0x0e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x52, 0x65, 0x73, 0x22, 0x0d, 0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x52, 0x65, 0x71, 0x22, 0x0d, 0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x52, 0x65, 0x73, 0x22, 0x73, 0x0a, 0x0f, 0x50, 0x61, 0x67, 0x65, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x03, 0x6f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x42, 0x07, 0xba, 0x48, 0x04, 0x32, 0x02, 0x20, 0x00, 0x52, 0x03, 0x6f, 0x69,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x12, 0x2d, 0x0a, 0x07, 0x73, 0x6f, 0x72,
	0x74, 0x5f, 0x62, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x06, 0x73, 0x6f, 0x72, 0x74, 0x42, 0x79, 0x22, 0xd3, 0x02, 0x0a, 0x09, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x03, 0x6f, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x70, 0x6c,
	0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x72, 0x65,
	0x70, 0x6c, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03,
	0x75, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x74, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09,
	0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x08, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x75, 0x69,
	0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x72, 0x75, 0x69, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x6c, 0x69, 0x6b, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x09, 0x6c, 0x69, 0x6b, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x68, 0x61, 0x74, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x09, 0x68, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x74, 0x69, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x6d, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x0d, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x15, 0x0a, 0x06, 0x69, 0x73, 0x5f, 0x70, 0x69,
	0x6e, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x69, 0x73, 0x50, 0x69, 0x6e, 0x22, 0x7e,
	0x0a, 0x0f, 0x50, 0x61, 0x67, 0x65, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x65,
	0x73, 0x12, 0x2f, 0x0a, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x69,
	0x65, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x63, 0x75, 0x72, 0x73, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x6e, 0x65, 0x78, 0x74, 0x43, 0x75, 0x72,
	0x73, 0x6f, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x68, 0x61, 0x73, 0x5f, 0x6e, 0x65, 0x78, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x68, 0x61, 0x73, 0x4e, 0x65, 0x78, 0x74, 0x22, 0x98,
	0x01, 0x0a, 0x12, 0x50, 0x61, 0x67, 0x65, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x03, 0x6f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x42, 0x07, 0xba, 0x48, 0x04, 0x32, 0x02, 0x20, 0x00, 0x52, 0x03, 0x6f, 0x69, 0x64,
	0x12, 0x20, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x42, 0x07, 0xba, 0x48, 0x04, 0x32, 0x02, 0x20, 0x00, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x74,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x12, 0x2d, 0x0a, 0x07, 0x73, 0x6f,
	0x72, 0x74, 0x5f, 0x62, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x06, 0x73, 0x6f, 0x72, 0x74, 0x42, 0x79, 0x22, 0x81, 0x01, 0x0a, 0x12, 0x50, 0x61,
	0x67, 0x65, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x73,
	0x12, 0x2f, 0x0a, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x65,
	0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x6e, 0x65, 0x78, 0x74, 0x43, 0x75, 0x72, 0x73,
	0x6f, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x68, 0x61, 0x73, 0x5f, 0x6e, 0x65, 0x78, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x68, 0x61, 0x73, 0x4e, 0x65, 0x78, 0x74, 0x2a, 0x23, 0x0a,
	0x08, 0x53, 0x6f, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x42, 0x79, 0x54,
	0x69, 0x6d, 0x65, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x42, 0x79, 0x54, 0x72, 0x65, 0x6e, 0x64,
	0x10, 0x01, 0x32, 0xb6, 0x04, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3c, 0x0a, 0x08,
	0x41, 0x64, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x17, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x65,
	0x71, 0x1a, 0x17, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x41,
	0x64, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x73, 0x12, 0x3c, 0x0a, 0x08, 0x44, 0x65,
	0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x17, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x1a,
	0x17, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x73, 0x12, 0x42, 0x0a, 0x0a, 0x4c, 0x69, 0x6b, 0x65,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x6b, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x1a, 0x19, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x4c,
	0x69, 0x6b, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x12, 0x4b, 0x0a, 0x0d,
	0x44, 0x69, 0x73, 0x6c, 0x69, 0x6b, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x73, 0x6c, 0x69,
	0x6b, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x73, 0x6c, 0x69, 0x6b, 0x65,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x12, 0x45, 0x0a, 0x0b, 0x52, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1a, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x73,
	0x12, 0x3c, 0x0a, 0x08, 0x50, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x17, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x69, 0x6e, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x73, 0x12, 0x48,
	0x0a, 0x0c, 0x50, 0x61, 0x67, 0x65, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1b,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x67, 0x65,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x73, 0x12, 0x51, 0x0a, 0x0f, 0x50, 0x61, 0x67, 0x65,
	0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1e, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x47, 0x65, 0x74,
	0x53, 0x75, 0x62, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x47, 0x65, 0x74,
	0x53, 0x75, 0x62, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x73, 0x42, 0x07, 0x5a, 0x05, 0x2e,
	0x2f, 0x73, 0x64, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_reply_proto_rawDescOnce sync.Once
	file_reply_proto_rawDescData = file_reply_proto_rawDesc
)

func file_reply_proto_rawDescGZIP() []byte {
	file_reply_proto_rawDescOnce.Do(func() {
		file_reply_proto_rawDescData = protoimpl.X.CompressGZIP(file_reply_proto_rawDescData)
	})
	return file_reply_proto_rawDescData
}

var file_reply_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_reply_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_reply_proto_goTypes = []interface{}{
	(SortType)(0),              // 0: comment.v1.SortType
	(*AddReplyReq)(nil),        // 1: comment.v1.AddReplyReq
	(*AddReplyRes)(nil),        // 2: comment.v1.AddReplyRes
	(*DelReplyReq)(nil),        // 3: comment.v1.DelReplyReq
	(*DelReplyRes)(nil),        // 4: comment.v1.DelReplyRes
	(*LikeActionReq)(nil),      // 5: comment.v1.LikeActionReq
	(*LikeActionRes)(nil),      // 6: comment.v1.LikeActionRes
	(*DislikeActionReq)(nil),   // 7: comment.v1.DislikeActionReq
	(*DislikeActionRes)(nil),   // 8: comment.v1.DislikeActionRes
	(*ReportReplyReq)(nil),     // 9: comment.v1.ReportReplyReq
	(*ReportReplyRes)(nil),     // 10: comment.v1.ReportReplyRes
	(*PinReplyReq)(nil),        // 11: comment.v1.PinReplyReq
	(*PinReplyRes)(nil),        // 12: comment.v1.PinReplyRes
	(*PageGetReplyReq)(nil),    // 13: comment.v1.PageGetReplyReq
	(*ReplyItem)(nil),          // 14: comment.v1.ReplyItem
	(*PageGetReplyRes)(nil),    // 15: comment.v1.PageGetReplyRes
	(*PageGetSubReplyReq)(nil), // 16: comment.v1.PageGetSubReplyReq
	(*PageGetSubReplyRes)(nil), // 17: comment.v1.PageGetSubReplyRes
}
var file_reply_proto_depIdxs = []int32{
	0,  // 0: comment.v1.PageGetReplyReq.sort_by:type_name -> comment.v1.SortType
	14, // 1: comment.v1.PageGetReplyRes.replies:type_name -> comment.v1.ReplyItem
	0,  // 2: comment.v1.PageGetSubReplyReq.sort_by:type_name -> comment.v1.SortType
	14, // 3: comment.v1.PageGetSubReplyRes.replies:type_name -> comment.v1.ReplyItem
	1,  // 4: comment.v1.Reply.AddReply:input_type -> comment.v1.AddReplyReq
	3,  // 5: comment.v1.Reply.DelReply:input_type -> comment.v1.DelReplyReq
	5,  // 6: comment.v1.Reply.LikeAction:input_type -> comment.v1.LikeActionReq
	7,  // 7: comment.v1.Reply.DislikeAction:input_type -> comment.v1.DislikeActionReq
	9,  // 8: comment.v1.Reply.ReportReply:input_type -> comment.v1.ReportReplyReq
	11, // 9: comment.v1.Reply.PinReply:input_type -> comment.v1.PinReplyReq
	13, // 10: comment.v1.Reply.PageGetReply:input_type -> comment.v1.PageGetReplyReq
	16, // 11: comment.v1.Reply.PageGetSubReply:input_type -> comment.v1.PageGetSubReplyReq
	2,  // 12: comment.v1.Reply.AddReply:output_type -> comment.v1.AddReplyRes
	4,  // 13: comment.v1.Reply.DelReply:output_type -> comment.v1.DelReplyRes
	6,  // 14: comment.v1.Reply.LikeAction:output_type -> comment.v1.LikeActionRes
	8,  // 15: comment.v1.Reply.DislikeAction:output_type -> comment.v1.DislikeActionRes
	10, // 16: comment.v1.Reply.ReportReply:output_type -> comment.v1.ReportReplyRes
	12, // 17: comment.v1.Reply.PinReply:output_type -> comment.v1.PinReplyRes
	15, // 18: comment.v1.Reply.PageGetReply:output_type -> comment.v1.PageGetReplyRes
	17, // 19: comment.v1.Reply.PageGetSubReply:output_type -> comment.v1.PageGetSubReplyRes
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_reply_proto_init() }
func file_reply_proto_init() {
	if File_reply_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_reply_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddReplyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reply_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddReplyRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reply_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelReplyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reply_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelReplyRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reply_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LikeActionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reply_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LikeActionRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reply_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DislikeActionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reply_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DislikeActionRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reply_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportReplyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reply_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportReplyRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reply_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PinReplyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reply_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PinReplyRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reply_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageGetReplyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reply_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplyItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reply_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageGetReplyRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reply_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageGetSubReplyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reply_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageGetSubReplyRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_reply_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reply_proto_goTypes,
		DependencyIndexes: file_reply_proto_depIdxs,
		EnumInfos:         file_reply_proto_enumTypes,
		MessageInfos:      file_reply_proto_msgTypes,
	}.Build()
	File_reply_proto = out.File
	file_reply_proto_rawDesc = nil
	file_reply_proto_goTypes = nil
	file_reply_proto_depIdxs = nil
}
